- hosts: all

  become: yes
  become_method: sudo
  become_user: root
  vars:
    ansible_become_password: "{{ lookup('env', 'SUDO_PASSWORD') }}"
  tasks:
    # Upgrade packages
    - name: upgrade apt packages
      become: true
      apt:
        upgrade: yes
        update_cache: yes
